# Generated by Django 4.1.3 on 2022-11-23 00:05

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c4ae44c2-cce0-48d9-ae4a-368bc285285b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e9396c59-5d7f-4197-bc94-ff01ddea18b9'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='work_out_date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 22, 19, 5, 45, 273842)),
        ),
    ]
