# Generated by Django 4.1.3 on 2022-11-23 01:34

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_alter_workout_id_alter_workoutplan_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6be21b70-fa87-4f46-8e97-8ec474f7f2d4'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='id',
            field=models.UUIDField(default=uuid.UUID('66d0a0fb-90ac-4de7-bfb0-0edc2c012aa8'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='work_out_date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 22, 20, 34, 28, 131098)),
        ),
    ]
