# Generated by Django 4.1.3 on 2022-11-23 00:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8a510785-afb7-420a-a9da-c2c7726e3baa'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='membershiptype',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a2ff70e8-bc1d-4545-9b02-0baac7917378'), editable=False, primary_key=True, serialize=False),
        ),
    ]
