# Generated by Django 4.1.3 on 2022-11-23 01:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_member_id_alter_membershiptype_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fd5d76e6-854f-433f-8b40-dd38e4e881f4'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='membershiptype',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e42bd179-07a3-42b2-be72-8bb7c8f19831'), editable=False, primary_key=True, serialize=False),
        ),
    ]
