# Generated by Django 4.1.3 on 2022-11-23 01:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('37b8a961-2c02-4788-a254-917d55cd6ede'), editable=False, primary_key=True, serialize=False),
        ),
    ]
