# Generated by Django 4.1.3 on 2022-11-22 23:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('2f0d41b9-81ae-4b44-8593-bcd80dd07362'), editable=False, primary_key=True, serialize=False)),
                ('instructor_name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
