# Generated by Django 4.1.3 on 2022-11-23 00:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f1193ddc-a6cc-4971-80b1-b463326ee3ac'), editable=False, primary_key=True, serialize=False),
        ),
    ]
