# Generated by Django 4.1.3 on 2022-11-22 23:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('be81599e-af51-480d-8f65-f1d4eff4b524'), editable=False, primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('payment_datetime', models.TimeField(default=datetime.datetime(2022, 11, 22, 18, 7, 25, 366012))),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
            ],
        ),
    ]
