# Generated by Django 4.1.3 on 2022-11-23 00:05

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('68b1be3e-5d9c-463a-95c5-e00ac0168cea'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_datetime',
            field=models.TimeField(default=datetime.datetime(2022, 11, 22, 19, 5, 45, 272843)),
        ),
    ]
