# Generated by Django 4.1.3 on 2022-11-23 01:34

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_payment_id_alter_payment_payment_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7f5cd103-dbb9-414d-ad61-30819180ba8e'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_datetime',
            field=models.TimeField(default=datetime.datetime(2022, 11, 22, 20, 34, 28, 130098)),
        ),
    ]
